Technical.UI/Controllers/BpkpController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Technical.UI.Models;
using Technical.UI.Services;
using Technical.UI.Services.IService;

namespace Technical.UI.Controllers
{
    public class BpkpController : Controller
    {
        private readonly IBpkpService _bpkpService;
        private readonly ILocationService _locationService;

        public BpkpController(IBpkpService bpkpService, ILocationService locationService)
        {
            this._bpkpService = bpkpService;
            this._locationService = locationService;
        }
        public async Task<IActionResult> List()
        {
            bool isLoggedInUser = User.IsInRole("Employee"); // Menentukan jika pengguna adalah Employee

            List<BpkpDto>? data = new();

            // Kirim parameter isLoggedInUser ke metode service
            ResponseDto? response = await _bpkpService.GetAllBpkp(isLoggedInUser);

            if (response != null && response.IsSuccess)
            {
                data = JsonConvert.DeserializeObject<List<BpkpDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }

            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            // Mendapatkan daftar lokasi
            var response = await _locationService.GetAllLocation();
            if (response?.IsSuccess == true)
            {
                var locations = JsonConvert.DeserializeObject<List<LocationDto>>(Convert.ToString(response.Result));
                ViewBag.Locations = locations.Select(x => new SelectListItem
                {
                    Text = x.locationName,
                    Value = x.LocationId
                }).ToList();
            }
            else
            {
                ViewBag.Locations = new List<SelectListItem>();
                TempData["error"] = response?.Message ?? "Failed to load locations.";
            }

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(BpkpCreateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _bpkpService.CreateBpkpAsync(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Bpkp Created Successfully";
                    return RedirectToAction(nameof(List)); // Redirect ke halaman lain jika diperlukan
                }
                else
                {
                    TempData["error"] = response?.Message ?? "Failed to create Bpkp";
                }
            }

            // Jika model tidak valid, reload lokasi
            var locationResponse = await _locationService.GetAllLocation();
            if (locationResponse?.IsSuccess == true)
            {
                var locations = JsonConvert.DeserializeObject<List<LocationDto>>(Convert.ToString(locationResponse.Result));
                ViewBag.Locations = locations.Select(x => new SelectListItem
                {
                    Text = x.locationName,
                    Value = x.LocationId
                }).ToList();
            }
            else
            {
                ViewBag.Locations = new List<SelectListItem>();
                TempData["error"] = locationResponse?.Message ?? "Failed to load locations.";
            }

            return View(model);
        }
    }
}

Technical.UI/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Technical.UI.Models;
using Technical.UI.Services.IService;

namespace Technical.UI.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILocationService _locationService;

        public LocationController(ILocationService locationService)
        {
            this._locationService = locationService;
        }
        public async Task<IActionResult> List()
        {
            List<LocationDto>? data = new();
            ResponseDto? response = await _locationService.GetAllLocation();
            if (response != null && response.IsSuccess)
            {
                data = JsonConvert.DeserializeObject<List<LocationDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }

            return View(data);
        }

        public async Task<IActionResult> Create(LocationDto model)
        {

            if (ModelState.IsValid)
            {
                ResponseDto? response = await _locationService.CreateLocationAsync(model);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Location created successfully";
                    return RedirectToAction(nameof(List));
                }
                else
                {
                    TempData["error"] = response?.Message ?? "Failed to create location.";
                }
            }
            return View(model);
        }


    }
}

Technical.UI/Views/Shared/_Layout.cshtml
@using Technical.UI.Utility;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Technical.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Technical.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Technical.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.RoleAdmin) || User.IsInRole(SD.RoleEmployee))
                        { 

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Location" asp-action="List">List Location</a></li>
                                <li><a class="dropdown-item" asp-controller="Location" asp-action="Create">Add Location</a></li>
                                <li><a class="dropdown-item" asp-controller="Bpkp" asp-action="List">List Bpkp</a></li>
                                <li><a class="dropdown-item" asp-controller="Bpkp" asp-action="Create">Add Bpkp</a></li>
                                
                            </ul>
                        </li>
                        }
                    </ul>
                    @{
                        var userName = User.Identity.Name; // Debug: Cek nilai
                    }
                    <div class="d-flex align-items-center">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="me-3 text-light">
                                <a class="nav-link" href="#">Hello, @userName</a>
                            </div>
                            <a class="btn me-3 bg-light text-dark"
                               asp-controller="Account"
                               asp-action="Logout">
                                Logout
                            </a>
                        }
                        else
                        {
                            <a class="btn me-3 bg-light text-dark"
                               asp-controller="Account"
                               asp-action="Login">
                                Login
                            </a>
                        }

                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Technical.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Technical.UI/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}